using System.Collections;
using UnityEngine;

public class MissileControl : MonoBehaviour
{
	public float missileSpeed;
	private Vector3 playerPos;
	private readonly float playerPosXClamp = 3.0f;
	private readonly float playerPosYClamp = 3.0f;

	private void MovingRestrictions()
	{
		//ï¿½Ïï¿½ï¿½Éï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ÌˆÊ’uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
		this.playerPos = transform.position;

		//playerPosï¿½Ïï¿½ï¿½ï¿½xï¿½ï¿½yï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½lï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
		//playerPos.xï¿½Æ‚ï¿½ï¿½ï¿½ï¿½lï¿½ï¿½-playerPosXClampï¿½`playerPosXClampï¿½ÌŠÔ‚Éï¿½ï¿½ß‚ï¿½
		this.playerPos.x = Mathf.Clamp(this.playerPos.x, -this.playerPosXClamp, this.playerPosXClamp);
		this.playerPos.y = Mathf.Clamp(this.playerPos.y, -this.playerPosYClamp, this.playerPosYClamp);

		transform.position = new Vector3(this.playerPos.x, this.playerPos.y, this.playerPos.z);
	}

	// speedï¿½ğ§Œä‚·ï¿½ï¿½
	public float speed = 10;
	public float moveForceMultiplier;

	// ï¿½ï¿½ï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½É‹@ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Eï¿½ÉŒï¿½ï¿½ï¿½ï¿½ï¿½gï¿½ï¿½ï¿½N
	public float yawTorqueMagnitude = 30.0f;

	// ï¿½ï¿½ï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½É‹@ï¿½ï¿½ï¿½ï¿½ã‰ºï¿½ÉŒï¿½ï¿½ï¿½ï¿½ï¿½gï¿½ï¿½ï¿½N
	public float pitchTorqueMagnitude = 60.0f;

	// ï¿½ï¿½ï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½É‹@ï¿½Ì‚ï¿½ï¿½ï¿½ï¿½Eï¿½ÉŒXï¿½ï¿½ï¿½ï¿½gï¿½ï¿½ï¿½N
	public float rollTorqueMagnitude = 30.0f;

	// ï¿½oï¿½lï¿½Ì‚æ‚¤ï¿½Épï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É–ß‚ï¿½ï¿½gï¿½ï¿½ï¿½N
	public float restoringTorqueMagnitude = 100.0f;

	private Vector3 Player_pos;
	private new Rigidbody rigidbody;

	void Awake()
	{
		rigidbody = GetComponent<Rigidbody>();

		// ï¿½oï¿½lï¿½ï¿½ï¿½ï¿½ï¿½Í‚Å‚ï¿½ï¿½ï¿½ï¿½hï¿½ê‘±ï¿½ï¿½ï¿½ï¿½Ì‚ï¿½hï¿½ï¿½ï¿½ï¿½ï¿½ßAangularDragï¿½ï¿½å‚«ï¿½ß‚É‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
		rigidbody.angularDrag = 15.0f;
	}

	void Update()
	{
		// ï¿½Oï¿½iï¿½Íï¿½ï¿½ï¿½
		transform.Translate(0f, 0f, missileSpeed * Time.deltaTime);

		this.MovingRestrictions();
	}

	void FixedUpdate()
	{
		float x = Input.GetAxis("Horizontal");
		float y = Input.GetAxis("Vertical");

		// xï¿½ï¿½yï¿½ï¿½speedï¿½ï¿½ï¿½|ï¿½ï¿½ï¿½ï¿½
		rigidbody.AddForce(x * speed, y * speed, 0);

		Vector3 moveVector = Vector3.zero;

		rigidbody.AddForce(moveForceMultiplier * (moveVector - rigidbody.velocity));

		// ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Ì“ï¿½ï¿½Í‚É‰ï¿½ï¿½ï¿½ï¿½Äpï¿½ï¿½ï¿½ï¿½ï¿½Ğ‚Ë‚ë‚¤ï¿½Æ‚ï¿½ï¿½ï¿½gï¿½ï¿½ï¿½N
		Vector3 rotationTorque = new Vector3(-y * pitchTorqueMagnitude, x * yawTorqueMagnitude, -x * rollTorqueMagnitude);

		// ï¿½ï¿½ï¿½İ‚Ìpï¿½ï¿½ï¿½Ì‚ï¿½ï¿½ï¿½É”ï¿½á‚µï¿½ï¿½ï¿½å‚«ï¿½ï¿½ï¿½Å‹tï¿½ï¿½ï¿½ï¿½ï¿½É‚Ğ‚Ë‚ë‚¤ï¿½Æ‚ï¿½ï¿½ï¿½gï¿½ï¿½ï¿½N
		Vector3 right = transform.right;
		Vector3 up = transform.up;
		Vector3 forward = transform.forward;
		Vector3 restoringTorque = new Vector3(forward.y - up.z, right.z - forward.x, up.x - right.y) * restoringTorqueMagnitude;

		// ï¿½@ï¿½Ì‚Éƒgï¿½ï¿½ï¿½Nï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
		rigidbody.AddTorque(rotationTorque + restoringTorque);
	}

	void OnCollisionEnter(Collision collision)
	{
		Time.timeScale = 0;
	}

}

/*
private float miuTurnInputValue;
private Rigidbody miuRb;
private float miuNoseInputValue;

public float missileSpeed;



// Start is called before the first frame update
void Start()
{
	miuRb = GetComponent<Rigidbody>();
}

// Update is called once per frame
void Update()
{
	// ï¿½Oï¿½iï¿½Íï¿½ï¿½ï¿½
	transform.Translate(0f, 0f , missileSpeed * Time.deltaTime);

	// ï¿½ï¿½ï¿½ï¿½
	miuTurnInputValue = Input.GetAxis("Horizontal");
	float turn = miuTurnInputValue * 150 * Time.deltaTime;
	Quaternion turnRotation = Quaternion.Euler(0, turn, 0);
	miuRb.MoveRotation(miuRb.rotation * turnRotation);

	// ï¿½@ï¿½ï¿½iï¿½ã¸ï¿½Aï¿½ï¿½ï¿½~ï¿½j
	miuNoseInputValue = Input.GetAxis("Vertical");
	float noseTurn = -miuNoseInputValue * 60 * Time.deltaTime;
	Quaternion turnNoseRotation = Quaternion.Euler(noseTurn, 0, 0);
	miuRb.MoveRotation(miuRb.rotation * turnNoseRotation);

 private Vector2 playerPos;
    private readonly float playerPosXClamp = 3.0f;
    private readonly float playerPosYClamp = 3.0f;

    private void Update()
    {
        ////ï¿½Oï¿½iï¿½ï¿½ï¿½ï¿½
        transform.Translate(Vector3.up * this.moveSpeed * Time.deltaTime);
        // ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        this.MovingRestrictions();

*/